name: Python CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Specify the Windows operating system

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Run tests
      run: pytest
